SUPABASE_URL = "https://ozgnbveyuquwqeokkkzk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96Z25idmV5dXF1d3Flb2tra3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNDgwNTMsImV4cCI6MjA2MzYyNDA1M30.dEn3z7CvnfhaKa4caPGDIfEjC3qvZiyjFQmpTv6O8eM"
